@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.chen1335.legendaryRelics.items.weapons;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;