@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.chen1335.legendaryRelics.registers.items.curios;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;