@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.chen1335.legendaryRelics.attachmentDatas;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;