@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.chen1335.legendaryRelics.registers.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;