@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.chen1335.legendaryRelics.compat.jei.recipeCategory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;