@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.chen1335.legendaryRelics.client.clientExtensions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;