@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.chen1335.legendaryRelics.registers.entities.projectiles;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;